name: Android CI (Zip Build)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK Command Line Tools
        run: |
          sudo mkdir -p /usr/local/android-sdk/cmdline-tools
          curl -fo tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip tools.zip -d /usr/local/android-sdk/cmdline-tools
          mv /usr/local/android-sdk/cmdline-tools/cmdline-tools /usr/local/android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=/usr/local/android-sdk" >> $GITHUB_ENV
          echo "/usr/local/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "/usr/local/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Accept licenses & install build tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.2"

      - name: Unzip project & move to repo root
        shell: bash
        run: |
          unzip -o ApneaTrainerProject.zip -d "$GITHUB_WORKSPACE"
          if [ -d "$GITHUB_WORKSPACE/ApneaTrainer" ]; then
            shopt -s dotglob
            mv "$GITHUB_WORKSPACE/ApneaTrainer/"* "$GITHUB_WORKSPACE"/
            rmdir "$GITHUB_WORKSPACE/ApneaTrainer"
          fi
          ls -la
          test -f "$GITHUB_WORKSPACE/build.gradle.kts" || (echo "HATA: build.gradle.kts kökte yok" && exit 1)

      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ApneaTrainer-debug-apk
          path: app/build/outputs/apk/debug/*.apk
