name: Android CI (Zip Build - Simple)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Android SDK + gerekli paketler (lisanslar otomatik kabul edilir)
      - name: Set up Android SDK (+packages)
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.2
            platform-tools
            cmdline-tools;latest

      # Zip'i aç ve proje köküne hizala
      - name: Unzip project & align root
        shell: bash
        run: |
          unzip -o ApneaTrainerProject.zip -d "$GITHUB_WORKSPACE"
          if [ -d "$GITHUB_WORKSPACE/ApneaTrainer" ]; then
            shopt -s dotglob
            mv "$GITHUB_WORKSPACE/ApneaTrainer/"* "$GITHUB_WORKSPACE"/
            rmdir "$GITHUB_WORKSPACE/ApneaTrainer"
          fi
          echo "Repo root listing:"
          ls -la
          test -f "$GITHUB_WORKSPACE/build.gradle.kts" || (echo "HATA: build.gradle.kts kökte yok" && exit 1)

      # Gradle wrapper olmadan Gradle 8.7 ile derle
      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ApneaTrainer-debug-apk
          path: app/build/outputs/apk/debug/*.apk
