name: Android CI (Zip Build)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install build tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.2"

      - name: Unzip project
        run: unzip -o ApneaTrainerProject.zip -d $GITHUB_WORKSPACE

      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ApneaTrainer-debug-apk
          path: app/build/outputs/apk/debug/*.apk
